apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboardVeiw
  labels:
    app: dashboardVeiw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboardVeiw
  template:
    metadata:
      labels:
        app: dashboardVeiw
    spec:
      containers:
        - name: dashboardVeiw
          image: username/dashboardVeiw:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5